name: GitHub-Profile-3D-Contrib

on:
  schedule: # 24:00 IST == 6:30 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.sanajitjana }}
      - name: Commit & Push
        run: |
          git config user.name sanajitjana
          git config user.email dev.sanajitjana@gmail.com
          git add -A .
          git commit -m "generated"
          git push
